POST http://localhost:3000/companies
content-type: application/json

{
	"cnpj": "51506255000161",
	"legalName": "Company Teste",
	"name": "Alan Turing",
	"cpf": "54772121285",
	"email": "alanturing@gmail.com"
}