POST http://localhost:3000/proposals
content-type: application/json

{
    "companyCnpj": "84207733000191",
    "employeeCpf": "52522513630",
    "totalLoanAmount": "300000",
    "numberOfInstallments": "1"
}